modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/GregTech-Intergalactical/TesseractAPI/issues"
license="LGPL-v3"

[[mods]]
modId="tesseractapi"
version="${version}"
displayName="TesseractAPI"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/GregTech-Intergalactical/TesseractAPI"
logoFile="assets/tesseractapi/icon.png"
authors="coderbot16, qubka, repolainen, mitchej123, Muramasa"
credits="Rongmario - cheerleading from the side"
description='''Powerful framework for energy, item, and fluid transport'''
[[dependencies.tesseractapi]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.tesseractapi]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,]"
    ordering="NONE"
    side="BOTH"