modLoader="javafml"
#loaderVersion="[${loader_version},)"
loaderVersion="[31,)"
issueTrackerURL="http://my.issue.tracker/"

[[mods]]
modId="tesseract"
#version="${version}"
version="0.0.1"
displayName="Tesseract API"
updateJSONURL="http://myurl.me/"
displayURL="http://example.com/"
logoFile="examplemod.png"
authors="coderbot16, mitchej123, Muramasa"
description='''Powerful framework for energy, item, and fluid transport'''
[[dependencies.tesseract]]
    modId="forge"
    mandatory=true
    #versionRange="[${forge_version},)"
    versionRange="31.0.1"
    ordering="NONE"
    side="BOTH"
[[dependencies.tesseract]]
    modId="minecraft"
    mandatory=true
    #versionRange="[${minecraft_version}]"
    versionRange="1.15.2"
    ordering="NONE"
    side="BOTH"